// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcFFPqrESk2d7LNeR9dRqJjb1ltyLZGtk',
    appId: '1:910529224036:web:6245645162b0749dd06e71',
    messagingSenderId: '910529224036',
    projectId: 'note-management-4fd69',
    authDomain: 'note-management-4fd69.firebaseapp.com',
    storageBucket: 'note-management-4fd69.firebasestorage.app',
    measurementId: 'G-MMMQQW5QTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy8Nqi2YpbLrBnZ13EhfK4ZxqUE463IUU',
    appId: '1:910529224036:android:1f2b02c0a1c9588ed06e71',
    messagingSenderId: '910529224036',
    projectId: 'note-management-4fd69',
    storageBucket: 'note-management-4fd69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKbbtfVh6Ij1JyRa_Nz-HVJ0FZigSRba8',
    appId: '1:910529224036:ios:4d920efd1cb5a294d06e71',
    messagingSenderId: '910529224036',
    projectId: 'note-management-4fd69',
    storageBucket: 'note-management-4fd69.firebasestorage.app',
    iosBundleId: 'com.example.noteManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKbbtfVh6Ij1JyRa_Nz-HVJ0FZigSRba8',
    appId: '1:910529224036:ios:4d920efd1cb5a294d06e71',
    messagingSenderId: '910529224036',
    projectId: 'note-management-4fd69',
    storageBucket: 'note-management-4fd69.firebasestorage.app',
    iosBundleId: 'com.example.noteManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcFFPqrESk2d7LNeR9dRqJjb1ltyLZGtk',
    appId: '1:910529224036:web:675abab06ac6626ed06e71',
    messagingSenderId: '910529224036',
    projectId: 'note-management-4fd69',
    authDomain: 'note-management-4fd69.firebaseapp.com',
    storageBucket: 'note-management-4fd69.firebasestorage.app',
    measurementId: 'G-1CK4134WEW',
  );
}
